from enum import StrEnum


class UserRole(StrEnum):
    FARMER = "FARMER"
    ADMIN = "ADMIN"


class Language(StrEnum):
    EN = "en"
    HI = "hi"
    MR = "mr"


class AreaUnit(StrEnum):
    ACRE = "ACRE"
    HECTARE = "HECTARE"
    GUNTHA = "GUNTHA"


class CropCycleStatus(StrEnum):
    PLANNED = "PLANNED"
    ACTIVE = "ACTIVE"
    HARVESTED = "HARVESTED"
    CANCELLED = "CANCELLED"


class SenderType(StrEnum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"
    SYSTEM = "SYSTEM"


class SessionOrigin(StrEnum):
    CATEGORY = "CATEGORY"
    FAQ = "FAQ"
    DIRECT = "DIRECT"
    OTHER = "OTHER"


class EvidenceStatus(StrEnum):
    SUFFICIENT = "SUFFICIENT"
    PARTIAL = "PARTIAL"
    INSUFFICIENT = "INSUFFICIENT"
    REQUIRES_LIVE_DATA = "REQUIRES_LIVE_DATA"
    REQUIRES_REGULATORY_VALIDATION = "REQUIRES_REGULATORY_VALIDATION"
    REQUIRES_IMAGE_ANALYSIS = "REQUIRES_IMAGE_ANALYSIS"
    LIVE_DATA_UNAVAILABLE = "LIVE_DATA_UNAVAILABLE"


class AttachmentType(StrEnum):
    IMAGE = "IMAGE"
    DOCUMENT = "DOCUMENT"


class AttachmentSource(StrEnum):
    UPLOAD = "UPLOAD"
    CAMERA = "CAMERA"
    DOCUMENT_PICKER = "DOCUMENT_PICKER"


class AttachmentStatus(StrEnum):
    PENDING_UPLOAD = "PENDING_UPLOAD"
    UPLOADED = "UPLOADED"
    PENDING_ANALYSIS = "PENDING_ANALYSIS"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class TrustStatus(StrEnum):
    APPROVED = "APPROVED"
    PENDING = "PENDING"
    DISABLED = "DISABLED"


class RecordStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    IMAGE_INSUFFICIENT = "IMAGE_INSUFFICIENT"


class SourceAccessMode(StrEnum):
    LIVE_API = "LIVE_API"
    STRUCTURED_DOWNLOAD = "STRUCTURED_DOWNLOAD"
    OFFICIAL_DOCUMENT = "OFFICIAL_DOCUMENT"
    OFFICIAL_HTML = "OFFICIAL_HTML"
    MANUAL_IMPORT = "MANUAL_IMPORT"
    NOT_TECHNICALLY_AVAILABLE = "NOT_TECHNICALLY_AVAILABLE"


class IngestionStatus(StrEnum):
    PENDING = "PENDING"
    FETCHING = "FETCHING"
    PROCESSING = "PROCESSING"
    EMBEDDING = "EMBEDDING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class TriggerType(StrEnum):
    CLI = "CLI"
    RETRY = "RETRY"
    REPROCESS = "REPROCESS"


class KnowledgeTopic(StrEnum):
    CROP_OVERVIEW = "CROP_OVERVIEW"
    CLIMATE = "CLIMATE"
    SOIL = "SOIL"
    LAND_PREPARATION = "LAND_PREPARATION"
    VARIETY = "VARIETY"
    SEED = "SEED"
    SEED_TREATMENT = "SEED_TREATMENT"
    SOWING = "SOWING"
    SPACING = "SPACING"
    INTERCROPPING = "INTERCROPPING"
    NUTRIENT_MANAGEMENT = "NUTRIENT_MANAGEMENT"
    FERTILIZER = "FERTILIZER"
    IRRIGATION = "IRRIGATION"
    DRAINAGE = "DRAINAGE"
    WEED_MANAGEMENT = "WEED_MANAGEMENT"
    PEST = "PEST"
    DISEASE = "DISEASE"
    CROP_STAGE = "CROP_STAGE"
    FLOWERING = "FLOWERING"
    POD_DEVELOPMENT = "POD_DEVELOPMENT"
    HARVEST = "HARVEST"
    POST_HARVEST = "POST_HARVEST"
    STORAGE = "STORAGE"
    PROCESSING = "PROCESSING"
    MILLING = "MILLING"
    OTHER = "OTHER"
