from enum import StrEnum


class UserRole(StrEnum):
    FARMER = "FARMER"
    ADMIN = "ADMIN"


class Language(StrEnum):
    EN = "en"
    HI = "hi"
    MR = "mr"


class AreaUnit(StrEnum):
    ACRE = "ACRE"
    HECTARE = "HECTARE"
    GUNTHA = "GUNTHA"


class CropCycleStatus(StrEnum):
    PLANNED = "PLANNED"
    ACTIVE = "ACTIVE"
    HARVESTED = "HARVESTED"
    CANCELLED = "CANCELLED"


class SenderType(StrEnum):
    USER = "USER"
    ASSISTANT = "ASSISTANT"
    SYSTEM = "SYSTEM"


class TrustStatus(StrEnum):
    APPROVED = "APPROVED"
    PENDING = "PENDING"
    DISABLED = "DISABLED"


class RecordStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class IngestionStatus(StrEnum):
    PENDING = "PENDING"
    FETCHING = "FETCHING"
    PROCESSING = "PROCESSING"
    EMBEDDING = "EMBEDDING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class TriggerType(StrEnum):
    CLI = "CLI"
    RETRY = "RETRY"
    REPROCESS = "REPROCESS"


class KnowledgeTopic(StrEnum):
    CROP_OVERVIEW = "CROP_OVERVIEW"
    CLIMATE = "CLIMATE"
    SOIL = "SOIL"
    LAND_PREPARATION = "LAND_PREPARATION"
    VARIETY = "VARIETY"
    SEED = "SEED"
    SEED_TREATMENT = "SEED_TREATMENT"
    SOWING = "SOWING"
    SPACING = "SPACING"
    INTERCROPPING = "INTERCROPPING"
    NUTRIENT_MANAGEMENT = "NUTRIENT_MANAGEMENT"
    FERTILIZER = "FERTILIZER"
    IRRIGATION = "IRRIGATION"
    DRAINAGE = "DRAINAGE"
    WEED_MANAGEMENT = "WEED_MANAGEMENT"
    PEST = "PEST"
    DISEASE = "DISEASE"
    CROP_STAGE = "CROP_STAGE"
    FLOWERING = "FLOWERING"
    POD_DEVELOPMENT = "POD_DEVELOPMENT"
    HARVEST = "HARVEST"
    POST_HARVEST = "POST_HARVEST"
    STORAGE = "STORAGE"
    PROCESSING = "PROCESSING"
    MILLING = "MILLING"
    OTHER = "OTHER"
