export type Language = "en" | "hi" | "mr";
export type EvidenceStatus = "SUFFICIENT" | "PARTIAL" | "INSUFFICIENT" | "REQUIRES_LIVE_DATA" | "REQUIRES_REGULATORY_VALIDATION" | "REQUIRES_IMAGE_ANALYSIS" | "LIVE_DATA_UNAVAILABLE";

export interface Profile { id: string; full_name: string; preferred_language: Language; state: string; district: string; taluka: string; village?: string | null; }
export interface Me { id: string; role: "FARMER" | "ADMIN"; phone_number?: string | null; email?: string | null; is_active: boolean; profile?: Profile | null; }
export interface Farm { id: string; name?: string | null; area_value: string; area_unit: "ACRE" | "HECTARE" | "GUNTHA"; state: string; district: string; taluka: string; village?: string | null; soil_type?: string | null; irrigation_type?: string | null; }
export interface CropCycle { id: string; farm_id: string; crop_name: string; crop_variety?: string | null; sowing_date: string; expected_harvest_date?: string | null; actual_harvest_date?: string | null; status: "PLANNED" | "ACTIVE" | "HARVESTED" | "CANCELLED"; estimated_crop_stage?: string | null; notes?: string | null; }
export interface Category { id: string; code: string; slug: string; title: string; description: string; icon_key?: string | null; display_order: number; requires_live_data: boolean; faq_count: number; }
export interface Citation { organization: string; document_title: string; source_url?: string | null; page_start?: number | null; page_end?: number | null; section?: string | null; }
export interface Faq { id: string; category_slug: string; question: string; answer: string; language: Language; evidence_status: EvidenceStatus; citations: Citation[]; }
export interface ChatSession { id: string; crop_cycle_id?: string | null; title?: string | null; language: Language; problem_category_id?: string | null; selected_faq_id?: string | null; origin_type: string; last_message_at?: string | null; is_archived: boolean; created_at: string; updated_at: string; }
export interface Message { id: string; chat_session_id: string; sender_type: "USER" | "ASSISTANT" | "SYSTEM"; content: string; language?: Language | null; intent?: string | null; evidence_status?: EvidenceStatus | null; citations?: Citation[]; created_at: string; }
export interface AssistanceResponse { message_id: string; session_id: string; answer: string; language: Language; intent: string; evidence_status: EvidenceStatus; citations: Citation[]; requires_follow_up: boolean; attachment_recommended: boolean; requires_live_data: boolean; requires_regulatory_validation: boolean; safety_flags: string[]; live_data: Record<string, unknown>[]; data_timestamp?: string | null; created_at: string; }
export interface SourceCapability { code: string; organization: string; status: "READY" | "BLOCKED" | "PARTIAL" | string; access_mode: string; source_url: string; detail?: string | null; }
export interface WeatherResponse { status: string; state: string; district: string; observations: Array<Record<string, unknown>>; retrieved_at: string; }
export interface MarketResponse { status: string; commodity: string; prices: Array<Record<string, unknown>>; retrieved_at: string; }
export interface ImageAnalysis { id: string; attachment_id?: string | null; status: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED" | "IMAGE_INSUFFICIENT"; observed_symptoms?: Record<string, unknown> | null; candidate_issues?: Array<Record<string, unknown>> | null; quality_assessment?: Record<string, unknown> | null; evidence_json?: Record<string, unknown> | null; error_code?: string | null; processed_at?: string | null; }
export type Screen = "login" | "help" | "home" | "weather" | "market" | "guidance" | "ask" | "crop" | "advisory" | "faqs" | "upload" | "history" | "notifications" | "profile";
